const routes = {
    home: '/',
    salesCounter: '/sales_counter',
    customerDetail: '/customer/:id',
    customerUpdate: '/customer/:id/edit',
    customerResponse: '/customer_response',
    dashboard: '/dashboard',
    productList: '/admin/base-products',
    productDetail1: '/admin/base-products/:id',
    productDetail2: '/admin/base-products/:id/variants/:variantId',
    productUpdate1: '/admin/base-products/:id/edit',
    productUpdate2: '/admin/base-products/:id/variants/:variantId/edit',
    productCreate: '/admin/base-products/create',
    import_order: '/import_order',
    detail_import_order: '/detail_import_order/:orderId',
    create_import_order: '/create_import_order',
    vendor_list: '/vendor_list',
    vendor_detail: '/vendor_detail/:vendorId',
    vendor_update: '/vendor_update/:vendorId',
    create_vendor: '/create_vendor',
    login: '/login',
    signup: '/signup',
    ordersReturn: '/order_returns',
    orderList: '/orders',
    order: '/order/:id',
    createReturnOrder: '/order_returns/create',
    orderReturnDetail: '/order_returns/:id',
    customerAll: '/customer_all',
    customerGroup: '/customer_group',
    customerCreateGroup: '//customer_group_create',
    customerDetailGroup: '/customer_group/:id',
    customerCreate: '/customer_create',
    statisticsGeneral: '/statistics_general',
    statisticsSales: '/statistics_sales',
    statisticsImport: '/statistics_import',
    balancesList: '/admin/balances',
    balancesCreate: '/admin/balances/create',
    balancesDetail: '/admin/balances/:id',
    staffList: '/admin/staffs',
    staffDetail: '/staffs/:id',
    shopInfo: '/shop',
    staffCreate: '/staffs/create',
    forbiden403:'/403',
    notfound404: '/*',
};

export default routes;
